POST http://localhost:3001/api/blogs 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI1ZWUwYmU2ZGZmOTUyOWEzY2E5NWFlOTQiLCJpYXQiOjE1OTE3ODcyNzF9.KVgjv1YgaxR0rZiohwqwumWroAe2vwmM7NXInV8WbBM 
content-type: application/json

{ "title": "Vegan Runners Blog", "author": "Friend of the Animals", "url": "http://www.vegetarianRunners.com", "likes": "5000" }