

POST http://localhost:3003/api/blogs 
content-type: application/json

{
"title": "Vegan Runners Blog", "author": "Friend of the Animals", "url": "http://www.vegetarianRunners.com", "likes": "5000"
}



     