
post http://localhost:3003/api/blogs
content-type: application/json


{       "title": "Runners Blog",
        "author": "Rita the Runner",
        "url": "http://runners.comh",
        "likes": 10000  }